language: scala
jdk: openjdk8
os: linux
dist: xenial
script:
  if [[ ! -z "$TRAVIS_TAG" ]]; then ./publish.sh; else ./make.sh; fi
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/1.0"
    - "$HOME/.embedpostgresql"
    - "$HOME/.sbt/boot"
    - "$HOME/.sbt/preloaded"
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
before_install:
  # https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_a4f2ea8de7e1_key -iv $encrypted_a4f2ea8de7e1_iv -in rings.tar.enc -out rings.tar -d; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then tar xvf rings.tar; fi
git:
  depth: false
branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
    - /^\d+\.\d+(\.\d+)?$/
