package org.apache.kafka.common;

/**
 * The sole purpose of this class is to remove a warning generated by
 * scalac about generating stubs for missing classes, the warning
 * is treated as an error, and the build fails
 */
public interface Configurable {
}
